Robustify service descriptors
proofpoint/platform pull request #829
Opened 2020-11-12 00:22 UTC by jcogilvie

Once upon a time we had a bug where we got a (mistakenly) empty set of descriptors and tried to run with it, replacing our correct-but-outdated list.  This patch should prevent a recurrence of said bug by allowing us to keep using expired descriptors if somebody tries to replace them with the empty set.  This should be considered a degraded mode of operation, but it's better than failing outright.

2020-11-12 00:32 UTC, johngmyers commented on discovery/src/main/java/com/proofpoint/discovery/client/ServiceDescriptorsUpdater.java
> +                if(serviceDescriptors.compareAndSet(null, newDescriptors)){
Please format with Proofpoint style

2020-11-12 00:42 UTC, johngmyers commented on discovery/src/main/java/com/proofpoint/discovery/client/ServiceDescriptorsUpdater.java
> +                if(serviceDescriptors.compareAndSet(null, newDescriptors)){
I don't think we need to do an atomic compareAndSet here. There won't be concurrent updates. We could simplify this to a single if condition and remove the duplicate code in the bodies.

2020-11-12 00:50 UTC, johngmyers commented on discovery/src/test/java/com/proofpoint/discovery/client/balancing/TestHttpServiceBalancerListenerAdapter.java
> +        Thread.sleep(10000);
Try replacing `executor` with a `SerialScheduledExecutorService` and call its `elapseTime()` method to advance time.

2020-11-12 16:29 UTC, jcogilvie commented
The CI build suggests the repocache is mad.  Spitting 500s.

```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.33.0:build (default) on project sample-server: Unable to pull 'repocache.nonprod.ppops.net/docker-remote/proofpoint/platform-zulu-11:1.11' from registry 'repocache.nonprod.ppops.net' : {"message":"Get http://repocache.nonprod.ppops.net/v2/: dial tcp 127.0.0.1:80: connect: connection refused"} (Internal Server Error: 500) -> [Help 1]
```

2020-12-02 19:47 UTC, johngmyers requested changes
There's just the code style issues.

2020-12-02 19:47 UTC, johngmyers commented on discovery/src/test/java/com/proofpoint/discovery/client/balancing/TestHttpServiceBalancerListenerAdapter.java
> +import static org.mockito.Mockito.*;
Proofpoint style prohibits wildcard imports. Please import the Proofpoint style.

2020-12-02 19:47 UTC, johngmyers commented on discovery/src/main/java/com/proofpoint/discovery/client/ServiceDescriptorsUpdater.java
> +                if(serviceDescriptors.get() == null || !newDescriptors.getServiceDescriptors().isEmpty()){
Please fix code style

2020-12-03 00:14 UTC, johngmyers approved these changes

2020-12-03 00:14 UTC, merged