disallow duplicate keys in json codec
proofpoint/platform pull request #843
Opened 2021-03-22 23:49 UTC by nr17

2021-03-23 00:01 UTC, gwittel commented
Was there a particular request/problem driving this change?  Strictly valid data is good, but given the lack of controls over the default codec behavior I'm a little concerned it will have surprise side effects.  In particular:

1. Services not having a way to disable this end to end.  Its a general problem since much of platform relies on the default, inaccessible/nonconfigurable ObjectMapper.
2. The [performance warning](https://fasterxml.github.io/jackson-core/javadoc/2.12/com/fasterxml/jackson/core/JsonParser.Feature.html#STRICT_DUPLICATE_DETECTION) in Jackson docs about this feature:
    >  Note that enabling this feature will incur performance overhead due to having to store and check additional information: this typically adds 20-30% to execution time for basic parsing.
3. Services don't necessarily have control over their data and must sometimes be tolerant of bad data rather than blowing up.

2021-03-23 00:31 UTC, johngmyers requested changes

2021-03-23 00:31 UTC, johngmyers commented on json/src/main/java/com/proofpoint/json/JsonCodec.java
> +import com.proofpoint.json.LengthLimitedWriter.LengthLimitExceededException;
The reordering of imports suggests that the Proofpoint code style hasn't been loaded.

2021-03-23 00:31 UTC, johngmyers commented on json/src/test/java/com/proofpoint/json/TestJsonCodec.java
> +        assertTrue(throwable.getMessage().contains("Duplicate field \'A\'"));
Why not use the `expectedExceptions` and `expectedExceptionsMessageRegExp` parameters of `@Test`?

2021-03-23 00:31 UTC, johngmyers commented on json/src/main/java/com/proofpoint/json/JsonCodec.java
> +            () -> new ObjectMapperProvider().get().enable(INDENT_OUTPUT).enable(JsonParser.Feature.STRICT_DUPLICATE_DETECTION))::get;
I don't see why this should be a quirk of JsonCodec. Why isn't it set in ObjectMapperProvider like all the other Features.

2021-03-23 00:32 UTC, nr17 commented
> Was there a particular request/problem driving this change? Strictly valid data is good, but given the lack of controls over the default codec behavior I'm a little concerned it will have surprise side effects. In particular:
> 
> 1. Services not having a way to disable this end to end.  Its a general problem since much of platform relies on the default, inaccessible/nonconfigurable ObjectMapper.
> 2. The [performance warning](https://fasterxml.github.io/jackson-core/javadoc/2.12/com/fasterxml/jackson/core/JsonParser.Feature.html#STRICT_DUPLICATE_DETECTION) in Jackson docs about this feature:
>    > Note that enabling this feature will incur performance overhead due to having to store and check additional information: this typically adds 20-30% to execution time for basic parsing.
> 3. Services don't necessarily have control over their data and must sometimes be tolerant of bad data rather than blowing up.

The original issue is that if there is a user-error in json, service will not know which config is effective and what other config gets discarded. This can happen with configuration files/input where there are duplicate keys in a potentially large json file. The current json codec behavior is to deduplicate it and present just one out of the duplicates.

There are few options

1. To keep the existing behavior, we could potentially add another way of achieving this where we have a new method : 

```
public JsonCodec<T> withoutDuplicate()
{
    return new JsonCodec<>(mapper.copy().enable(JsonParser.Feature.STRICT_DUPLICATE_DETECTION), type);
}
```
2. Change the default behavior, and provide a method to discard duplicate keys. 

I would assume that people would not unknowingly want to discard duplicate keys. But I can understand the performance issue and the requirement for tolerating bad data.

2021-03-23 00:40 UTC, johngmyers commented
I believe the main driver of this is config files, but the issue exists for APIs as well.

RFC 8259 states "When the names within an object are not unique, the behavior of software that receives such an object is unpredictable."

We already disable `DeserializationFeature.ACCEPT_FLOAT_AS_INT` in `ObjectMapperProvider.get()`, so we already have a stance of strictness in parsing.

2021-03-23 00:53 UTC, johngmyers commented on json/src/main/java/com/proofpoint/json/JsonCodec.java
> +            () -> new ObjectMapperProvider().get().enable(INDENT_OUTPUT).enable(JsonParser.Feature.STRICT_DUPLICATE_DETECTION))::get;
I think we should be setting `DeserializationFeature.FAIL_ON_READING_DUP_TREE_KEY` instead.

2021-03-23 01:14 UTC, nr17 commented on json/src/main/java/com/proofpoint/json/JsonCodec.java
> +            () -> new ObjectMapperProvider().get().enable(INDENT_OUTPUT).enable(JsonParser.Feature.STRICT_DUPLICATE_DETECTION))::get;
This doesn't work as it requires us to deserialize the json string/input to jackson json tree first and then to the POJO. Currently we are calling ObjectMapper.readValue(json, javaType) instead of JsonParser.readValueAsTree(). 
If we change, we'll have to do something like this:
```
        JsonParser jsonParser = < ... > // create a new instance with json bytes ? have to look into it. mapper.getJsonFactory().createJsonParser(writeValueAsBytes(pojo));

        JsonNode tree = jsonParser.readValueAsTree();  // --> catch the exception here
        return  jsonParser.getCodec().treeToValue(tree, MyPOJO.class);
```

This might have performance impact.

2021-03-23 23:01 UTC, johngmyers commented on json/src/test/java/com/proofpoint/json/TestJsonCodec.java
> +        assertTrue(throwable.getMessage().contains("Duplicate field \'A\'"));
This should use `JsonTester.decodeJson()` instead of using a string constant.

2021-03-23 23:01 UTC, johngmyers commented on json/src/test/java/com/proofpoint/json/PersonMap.java
> +    private int id;
This is extraneous to the test.

2021-03-23 23:03 UTC, johngmyers commented on json/src/test/java/com/proofpoint/json/PersonMap.java
> +    private Map<String, Person> persons;
This shows poor practice in deserialization codecs. The object should be immutable. Use a `@JsonCreator` instead.

2021-03-24 00:14 UTC, johngmyers commented on json/src/main/java/com/proofpoint/json/JsonCodec.java
> +            () -> new ObjectMapperProvider().get().enable(INDENT_OUTPUT).enable(JsonParser.Feature.STRICT_DUPLICATE_DETECTION))::get;
I've been delving into the databind code and it doesn't look very consistent about when it tests the `FAIL_ON_READING_DUP_TREE_KEY` feature. In particular, `BeanDeserializer` doesn't test it, so it won't be effective for `Person`.

I did find that if the codec is defined as taking an `ImmutableMap` instead of a `Map` then one gets the desired exception. This is because `ImmutableMapBuilder.put()` disallows duplicate keys. Perhaps that would be a better way to approach the problem.

2021-03-24 00:44 UTC, nr17 commented on json/src/main/java/com/proofpoint/json/JsonCodec.java
> +import com.proofpoint.json.LengthLimitedWriter.LengthLimitExceededException;
Can you point me to the code style file. I have one file already loaded and it is called PFPT. I obtained it from scancloud project. The sort order of imports is slightly different in that. https://wiki.proofpoint.com/wiki/display/ENG/Java+Code+Style#JavaCodeStyle-Imports suggests existence of the file: "Code style for IntelliJ is tracked in Git".

2021-03-24 06:11 UTC, nr17 commented on json/src/test/java/com/proofpoint/json/TestJsonCodec.java
> +        assertTrue(throwable.getMessage().contains("Duplicate field \'A\'"));
decodeJson itself calls codec.fromJson which we want to test here.

2021-03-24 16:08 UTC, johngmyers commented on json/src/test/java/com/proofpoint/json/TestJsonCodec.java
> +        assertTrue(throwable.getMessage().contains("Duplicate field \'A\'"));
The test here uses JSON encoded as a string literal, which is hard to read and maintain. `JsonTester.decodeJson()` has tests represent the JSON they want to test as much more readable POJO. See https://wiki.proofpoint.com/wiki/display/iEng/JSON+serialization+with+Jackson

2021-03-24 17:30 UTC, nr17 commented on json/src/test/java/com/proofpoint/json/TestJsonCodec.java
> +        assertTrue(throwable.getMessage().contains("Duplicate field \'A\'"));
I had considered the TestPersonRepresentation example after receiving your comments. Since the json itself is invalid due to duplicate keys, I don't know how to represent that in a readable POJO (hashMap). Do you have any suggestion?

2021-03-24 17:49 UTC, johngmyers commented on json/src/test/java/com/proofpoint/json/TestJsonCodec.java
> +        assertTrue(throwable.getMessage().contains("Duplicate field \'A\'"));
Ah, good point. I wonder how multimaps serialize.

2021-03-24 17:50 UTC, johngmyers commented on json/src/main/java/com/proofpoint/json/ObjectMapperProvider.java
> +        objectMapper.enable(DeserializationFeature.FAIL_ON_READING_DUP_TREE_KEY);
Why is this still needed?

2021-03-24 18:26 UTC, nr17 commented on json/src/main/java/com/proofpoint/json/ObjectMapperProvider.java
> +        objectMapper.enable(DeserializationFeature.FAIL_ON_READING_DUP_TREE_KEY);
didn't realize that it was working just because of changing from Map to ImmutableMap. Removed it now.

2021-03-30 18:01 UTC, merged