Reporting branch for Splunk Observability added
proofpoint/platform pull request #883
Opened 2022-08-26 17:07 UTC by ehatch90

This includes reporting for datapoints and events to Splunk Observability with little to no changes required by currrent platform users. This new branch is heavily patterned after the current reporting-client branch to facilitate that easy switch over for users. Currently gathered data is forrmatted to Splunk JSON and reported there. A splunk observability realm/url and auth token will need to be provided to write to splunk.

2022-08-26 18:55 UTC, johngmyers requested changes

2022-08-26 18:55 UTC, johngmyers commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +                builder.put(dimensionName, enforceLengthMaximum(dimensionValue, MAX_DIMENSION_VALUE_LENGTH));
I'm concerned that the subsequent `builder.build()` could throw `IllegalArgumentException` in the case where multiple `dimensionName` values get stripped down to duplicate values.

2022-08-26 18:55 UTC, johngmyers commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClientConfig.java
> +    @Config("reporting.enabled")
Should we share this property with Pulse?

2022-08-30 19:08 UTC, ehatch90 commented on reporting-splunk-observability/pom.xml
> +        <maven.compiler.target>13</maven.compiler.target>
changed

2022-08-30 19:08 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/ReportingSplunkObservabilityModule.java
> +        discoveryBinder(binder).bindDiscoveredHttpClient("reporting", ForSplunkObservabilityClient.class);
added, syntax was slightly different so may want to double check that I got what you intended.

2022-08-30 19:09 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/ReportingSplunkObservabilityModule.java
> +        return newSingleThreadScheduledExecutor(daemonThreadsNamed("reporting-collector-%s"));
changed, hopefully this is a better name but it will at least be different.

2022-08-30 19:12 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        this.authToken = splunkObservabilityClientConfig.getAuthToken();
Changed, thanks for helping me shorten this up.

2022-08-30 19:13 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        while(iterator.hasNext()) {
I found and loaded the code style into my IDE. Hopefully it is cleaner now.

2022-08-30 19:13 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +            } else {
fixed

2022-08-30 19:13 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +                    logger.warn("Dropped string datapoint before report. String value empty, name: %s", cell.getRowKey());
Shortened, I think it is more brief but still gives enough info now.

2022-08-30 19:14 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        if (numDatapoints > 0) {
Great suggestion, I have added the empty check. It looks much cleaner now, thanks.

2022-08-30 19:17 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +                builder.put(dimensionName, enforceLengthMaximum(dimensionValue, MAX_DIMENSION_VALUE_LENGTH));
Immutable Table Builder didn't have any sort of get functionality so I couldn't check if something was already in it. I have switched to a HashMap, used putIfAbsent, and included a log message if a duplicate dimension name is dropped. Let me know if this isn't the solution you had in mind or if there is a better way you would recommend.

2022-08-30 19:17 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClientConfig.java
> +    @Config("reporting.enabled")
Changed to avoid any conflict.

2022-08-30 19:20 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +                builder.put(dimensionName, enforceLengthMaximum(dimensionValue, MAX_DIMENSION_VALUE_LENGTH));
I also included a test case to verify that the exception would originally be thrown and you were correct that it would be. The test now passes with the new code using the hashmap. Thanks a ton for the catch on this one.

2022-09-21 21:10 UTC, johngmyers commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClientConfig.java
> +@DefunctConfig("report.uri")
I don't think you need `@DefunctConfig` on a new config class.

2022-09-21 21:10 UTC, johngmyers commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/ReportingSplunkObservabilityModule.java
> +        httpClientBinder(binder).bindBalancingHttpClient("splunk-observability", ForSplunkObservabilityClient.class);
You might want to make this module an `AbstractConfigurationAwareModule` to avoid binding this when splunk is configured disabled. Otherwise this binding will require the URI to be configured, even if splunk is disabled.

2022-09-22 16:51 UTC, ehatch90 commented on pom.xml
> +        <module>reporting-splunk-observability</module>
The only reason I avoided doing that is that it creates ambiguity between splunk, the logging product, and splunk ,the telemetry product. I will change it if we're not concerned about that ambiguity. I get that this could be inferred by context and endpoints going to telemetry endpoints but the idea is that it would be clearer by name, at a glance.

2022-09-23 16:51 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +                if (checkEmpty.length() == 0) {
Yes the API rejects it and I think it does it silently so I wanted to have some log of the datapoint being lost.

2022-09-29 18:03 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        this.objectMapper = objectMapper;
added, thanks.

2022-09-29 18:04 UTC, ehatch90 commented on reporting-splunk-observability/pom.xml
> +    </properties>
moved under reporting-client. This file no longer exists.

2022-09-29 18:04 UTC, ehatch90 commented on reporting-splunk-observability/pom.xml
> +        </dependency>
Re-homed into reporting-client to eliminate some of this confusion.

2022-09-29 18:05 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        while (iterator.hasNext()) {
I have moved this to a stream implementation. Please look it over and see if it's similar to what you had in mind.

2022-09-29 18:06 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        ImmutableTable.Builder<String, Map<String, String>, Object> collectedEvents = ImmutableTable.builder();
Stream implementation mentioned above.

2022-09-29 18:08 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        }
added

2022-09-29 18:11 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/SplunkObservabilityClientConfig.java
> +@DefunctConfig("report.uri")
Changed to @ConfigDescription. @Config seemed right but couldn't be applied here because it couldn't be applied to an ElementType.TYPE. Hopefully this is a correct shift/what you intended.

2022-09-29 18:13 UTC, ehatch90 commented on reporting-splunk-observability/src/main/java/com/proofpoint/reporting/ReportingSplunkObservabilityModule.java
> +        httpClientBinder(binder).bindBalancingHttpClient("splunk-observability", ForSplunkObservabilityClient.class);
Changed to AbstractConfigurationAwareModule, as requested. Thank you for catching that depedency problem.

2022-10-05 16:41 UTC, johngmyers requested changes

2022-10-05 16:41 UTC, johngmyers commented on reporting-client/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        this.authToken = requireNonNull(splunkObservabilityClientConfig.getAuthToken(), "splunkObservabilityClientConfig.auth-token is null");
Put a `@NotNull` (and possibly `@NotEmpty`) annotation on `SplunkObservabilityClientConfig.getAuthToken()` instead. That will give better diagnostics.

2022-10-05 16:41 UTC, johngmyers commented on reporting-client/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +                .filter(cell -> cell.getValue() instanceof Number).collect(ImmutableTable.toImmutableTable(
```suggestion
                .filter(cell -> cell.getValue() instanceof Number)
                .collect(ImmutableTable.toImmutableTable(
```

2022-10-05 16:41 UTC, johngmyers commented on reporting-client/src/main/java/com/proofpoint/reporting/SplunkObservabilityClientConfig.java
> +@ConfigDescription("report.uri")
This seems unnecessary?

2022-10-06 17:53 UTC, ehatch90 commented on reporting-client/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        this.authToken = requireNonNull(splunkObservabilityClientConfig.getAuthToken(), "splunkObservabilityClientConfig.auth-token is null");
When I add the two annotations above `@NotNull` and `@NotEmpty` and change the line over to:
`this.authToken = splunkObservabilityClientConfig.getAuthToken();` . The sample server will run fine but I have a test case that fails in TestSplunkObservabilityClientConfig - testLegacyProperties. It complains about missing required configuration for the auth token(full error output from test case at bottom). I think this means that it wouldn't be legacy compatible.

Seems that if I include both checks by adding the annotations and keeping the requireNonNull check I still have that problem with the testLegacyProperties test case, so that seems to not be a possible solution. 

Should I revert to just the requireNonNull check for compatability with legacyProperties, remove this test case as no longer needed, or am I not seeing a way that this test case should be tuned up to still provide this check but not throw an unnecessary error?

`Oct 06, 2022 11:49:13 AM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 7.0.1.Final

com.google.inject.ConfigurationException: Guice configuration errors:

1) Error: Missing required configuration property 'splunk-observability.auth-token' (for class SplunkObservabilityClientConfig.authToken)

2) Error: Invalid configuration property 'splunk-observability.auth-token': must not be empty (for class SplunkObservabilityClientConfig.authToken)

2 errors

======================
Full classname legend:
======================
SplunkObservabilityClientConfig: "com.proofpoint.reporting.SplunkObservabilityClientConfig"
========================
End of classname legend:
========================


	at com.proofpoint.configuration.Problems.getException(Problems.java:126)
	at com.proofpoint.configuration.Problems.throwIfHasErrors(Problems.java:70)
	at com.proofpoint.configuration.ConfigurationFactory.build(ConfigurationFactory.java:156)
	at com.proofpoint.configuration.ConfigurationFactory.build(ConfigurationFactory.java:133)
	at com.proofpoint.configuration.testing.ConfigAssertions.newInstance(ConfigAssertions.java:406)
	at com.proofpoint.configuration.testing.ConfigAssertions.assertLegacyEquivalence(ConfigAssertions.java:155)
	at com.proofpoint.reporting.TestSplunkObservabilityClientConfig.testLegacyProperties(TestSplunkObservabilityClientConfig.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:806)
	at org.testng.TestRunner.run(TestRunner.java:601)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
`

2022-10-07 17:21 UTC, johngmyers commented on reporting-client/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        this.authToken = requireNonNull(splunkObservabilityClientConfig.getAuthToken(), "splunkObservabilityClientConfig.auth-token is null");
See https://github.com/proofpoint/platform/blob/f5312cff7a1abae936377876b5fc873fd6d7b975/http-client/src/test/java/com/proofpoint/http/client/balancing/TestHttpServiceBalancerUriConfig.java#L40

2022-10-10 22:18 UTC, ehatch90 commented on pom.xml
> +        <module>reporting-splunk-observability</module>
removed, sorry I missed that after moving the code into reporting-client.

2022-10-10 22:18 UTC, ehatch90 commented on reporting-client/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        this.authToken = requireNonNull(splunkObservabilityClientConfig.getAuthToken(), "splunkObservabilityClientConfig.auth-token is null");
Thanks, I have included this and the test is working fine.

2022-10-10 22:18 UTC, ehatch90 commented on reporting-client/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +                .filter(cell -> cell.getValue() instanceof Number).collect(ImmutableTable.toImmutableTable(
Fixed

2022-10-10 22:18 UTC, ehatch90 commented on reporting-client/src/main/java/com/proofpoint/reporting/SplunkObservabilityClientConfig.java
> +@ConfigDescription("report.uri")
Agreed, it has been removed.

2022-10-11 22:07 UTC, johngmyers approved these changes

2022-10-11 22:16 UTC, johngmyers requested changes

2022-10-11 22:16 UTC, johngmyers commented on reporting-client/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        }
nit: blank line after

2022-10-11 22:16 UTC, johngmyers commented on reporting-client/src/main/java/com/proofpoint/reporting/SplunkObservabilityClientConfig.java
> +    }
nit: blank line after

2022-10-11 22:16 UTC, johngmyers commented on reporting-client/src/test/java/com/proofpoint/reporting/TestSplunkObservabilityClient.java
> +                sentDataPointsJson = Maps.newHashMap(sentDataPointsJson);
Please fix or suppress the modernizer error here.

2022-10-20 15:52 UTC, ehatch90 commented on reporting-client/src/main/java/com/proofpoint/reporting/SplunkObservabilityClient.java
> +        }
added

2022-10-20 15:52 UTC, ehatch90 commented on reporting-client/src/main/java/com/proofpoint/reporting/SplunkObservabilityClientConfig.java
> +    }
added

2022-10-20 17:09 UTC, ehatch90 commented on reporting-client/src/test/java/com/proofpoint/reporting/TestSplunkObservabilityClient.java
> +                sentDataPointsJson = Maps.newHashMap(sentDataPointsJson);
Seeing that the checks passed and running the modernizer locally seemed to work. I think this is fixed.

2022-10-20 17:19 UTC, johngmyers approved these changes

2022-10-20 17:19 UTC, merged