Session handler
proofpoint/platform pull request #895
Opened 2022-11-23 09:45 UTC by tomjshore

This injects SessionHandler into HttpServer.

2022-11-28 19:41 UTC, johngmyers requested changes

2022-11-28 19:41 UTC, johngmyers commented on http-server/src/main/java/com/proofpoint/http/server/HttpServer.java
> +         *           |       |--- session handler
```suggestion
         *           |       |--- session handler (optional)
```

2022-11-29 13:46 UTC, tomjshore commented on http-server/src/main/java/com/proofpoint/http/server/HttpServer.java
> +         *           |       |--- session handler
Added in comment and put the method withSessionHandler.

2022-12-01 18:04 UTC, johngmyers requested changes
Please rebase to remove the merge commit.

2022-12-01 18:04 UTC, johngmyers commented on http-server/src/main/java/com/proofpoint/http/server/HttpServerModule.java
> +    public HttpServerModule withSessionHandler(SessionHandler sessionHandler)
This shouldn't take arguments.

If the application is providing a SessionHandler, it should bind it itself so that it can use Guice to construct it. This option makes sense if the application needs to do application-specific customization of the SessionHandler.

If the SessionHandler does not need customization, then there should be a `withSessionHandler()` method taking no parameters that causes `HttpServerModule` to bind it.

Requiring the application to construct a `SessionHandler` to pass to the module means the application cannot construct the `SessionHandler` with Guice.

2022-12-01 18:04 UTC, johngmyers commented on http-server/src/test/java/com/proofpoint/http/server/TestHttpServerModule.java
> +    Map<String, String> properties;
Shouldn't this be `private`?

2022-12-01 18:04 UTC, johngmyers commented on http-server/src/test/java/com/proofpoint/http/server/TestHttpServerModule.java
> +                "http-server.log.path", new File(tempDir, "http-request.log").getAbsolutePath());
Good refactor, thanks!

2022-12-02 16:26 UTC, tomjshore commented on http-server/src/test/java/com/proofpoint/http/server/TestHttpServerModule.java
> +    Map<String, String> properties;
Yes and Done

2022-12-02 16:27 UTC, tomjshore commented on http-server/src/main/java/com/proofpoint/http/server/HttpServerModule.java
> +    public HttpServerModule withSessionHandler(SessionHandler sessionHandler)
Ok Done

2022-12-02 16:27 UTC, tomjshore commented on http-server/src/main/java/com/proofpoint/http/server/HttpServerProvider.java
> +    public void setSessionHandler(SessionHandler sessionHandler){
Done

2022-12-02 16:27 UTC, tomjshore commented on http-server/src/main/java/com/proofpoint/http/server/HttpServer.java
> +        handlers.addHandler(createServletContext(theServlet, parameters, false, filters, queryStringFilter, loginService, nodeInfo, sessionHandler,"http", "https"));
Done

2022-12-02 16:27 UTC, tomjshore commented on http-server/src/main/java/com/proofpoint/http/server/HttpServer.java
> +            rootHandlers.addHandler(createServletContext(theAdminServlet, adminParameters, true, adminFilters, queryStringFilter, loginService, nodeInfo, null,"admin"));
Done

2022-12-02 16:27 UTC, tomjshore commented on http-server/src/main/java/com/proofpoint/http/server/HttpServerModule.java
> +        if(sessionHandler != null){
Done

2022-12-06 03:35 UTC, johngmyers commented on http-server/src/main/java/com/proofpoint/http/server/HttpServerModule.java
> +        }
Please avoid unnecessary use of instance bindings. See https://github.com/google/guice/wiki/InstanceBindings

```suggestion
            if (bindSessionHandler) {
                binder.bind(SessionHandler.class).in(Scopes.SINGLETON)
            }
```

2022-12-07 19:09 UTC, johngmyers approved these changes

2022-12-07 19:21 UTC, merged