Upgrade modernizer and jacoco to support Java 17
proofpoint/platform pull request #907
Opened 2023-03-08 16:19 UTC by tomjshore

When we have a project on Java 17 and the parent pom is platform, we find that modernizer and jacoco do not run correctly. 

For example
```Execution modernizer of goal org.gaul:modernizer-maven-plugin:2.2.0:modernizer failed: Unsupported class file major version 61```

To fix this I have upgraded jacoco and modernizer.

Because I have updated modernizer I had to fix some bits of the code to compile with new modernizer rules.

2023-03-08 17:10 UTC, johngmyers requested changes

2023-03-08 17:10 UTC, johngmyers commented on discovery/src/main/java/com/proofpoint/discovery/client/testing/StaticServiceSelector.java
> +    public StaticServiceSelector(Collection<ServiceDescriptor> serviceDescriptors)
This appears to be an incompatible change.

2023-03-08 17:10 UTC, johngmyers commented on reporting-prometheus/src/main/java/com/proofpoint/reporting/MetricsResource.java
> +                                Stream.concat(taggedValue.getTags().entrySet().stream(), instanceTags.entrySet().stream()).collect(Collectors.toList()),
This will cause the tags to be copied to a newly allocated `List` instead of allowing the writer to iterate over the concatination.

2023-03-13 10:25 UTC, tomjshore commented on reporting-prometheus/src/main/java/com/proofpoint/reporting/MetricsResource.java
> +                                Stream.concat(taggedValue.getTags().entrySet().stream(), instanceTags.entrySet().stream()).collect(Collectors.toList()),
Yep ok I have reverted this back and added an exception to this rule in the pom modernizer section.

2023-03-13 10:26 UTC, tomjshore commented on discovery/src/main/java/com/proofpoint/discovery/client/testing/StaticServiceSelector.java
> +    public StaticServiceSelector(Collection<ServiceDescriptor> serviceDescriptors)
I was playing around with this in an early commit.  You should see now that the signature is back to Iterable.

2023-03-23 11:19 UTC, tomjshore commented
This ticket is ready to be reviewed again.

2023-07-31 17:19 UTC, johngmyers approved these changes

2023-07-31 17:20 UTC, merged