Changes required to upgrade Jetty to 10.0.15
proofpoint/platform pull request #911
Opened 2023-04-28 04:21 UTC by gdasbach

2023-04-28 04:25 UTC, gdasbach commented
Some commented areas should be discussed and finalized before merging
* Removal of connection pool active requests in dump details
* Choice of excluding javax.servlet API (max 4.0.1), and keeping jetty's servlet API from toolchain (version 4.0.6)

2023-04-28 21:19 UTC, johngmyers commented on http-client/src/main/java/com/proofpoint/http/client/jetty/JettyHttpClient.java
> +        /* TODO: Need a better way to dump active requests due to getActiveConnections being removed
See Airlift. They drop a class into the eclipse package in order to export that private state.

2023-04-28 21:19 UTC, johngmyers commented on http-server/src/main/java/com/proofpoint/http/server/HttpServer.java
>          sslContextFactory.setKeyStorePassword(config.getKeystorePassword());
We should remove the `if (!isJava8) {` test below as it will never be java8.

2023-04-28 21:22 UTC, johngmyers commented
I think we want to keep with the official javax.servlet API for now. We can switch to Jetty's servlet API when we go to Jetty 11 if need be. We should only do one servlet transition, as the one will be painful enough as is.

2023-05-01 13:07 UTC, gdasbach commented on http-client/src/main/java/com/proofpoint/http/client/jetty/JettyHttpClient.java
> +        /* TODO: Need a better way to dump active requests due to getActiveConnections being removed
Yeah, wasn't sure on whether we wanted to copy that behavior given that Jetty was explicitly hiding the implementation details, but easy enough to add

2023-05-01 14:05 UTC, gdasbach commented on http-client/src/main/java/com/proofpoint/http/client/jetty/JettyHttpClient.java
> +            HTTP2Client client = new HTTP2Client(clientConnector);
So airlift's experimental http/2 support excludes https by default, which is why this differs (and there is a strong assertion in the latest code to prevent secure connections for http2.  We look to have added https support for http2 connections, and added explicit unit tests around that support.  So really depends on whether we want to keep the https support for http2 or remove it, and the associated tests.

2023-05-01 15:14 UTC, gdasbach commented on http-client/src/main/java/com/proofpoint/http/client/jetty/JettyHttpClient.java
> +        /* TODO: Need a better way to dump active requests due to getActiveConnections being removed
Done

2023-05-01 15:15 UTC, gdasbach commented on http-server/src/main/java/com/proofpoint/http/server/HttpServer.java
>          sslContextFactory.setKeyStorePassword(config.getKeystorePassword());
Done

2023-05-01 15:17 UTC, gdasbach commented
> I think we want to keep with the official javax.servlet API for now. We can switch to Jetty's servlet API when we go to Jetty 11 if need be. We should only do one servlet transition, as the one will be painful enough as is.

Re-added the javax.servlet-api, for version 4, and excluded the jetty toolchain implementation.  One consideration is that the jetty version supports JPMS, which the J2EE implementation won't support until version 6, I believe.  I don't think we're really using JPMS yet, so probably won't be a showstopper

2023-05-01 20:01 UTC, johngmyers requested changes

2023-05-01 21:02 UTC, johngmyers commented on http-client/src/main/java/com/proofpoint/http/client/jetty/JettyHttpClient.java
> +        getActiveConnections((AbstractConnectionPool) httpDestination.getConnectionPool()).stream()
Need to `import org.eclipse.jetty.client.AbstractConnectionPool;`

2023-05-01 21:10 UTC, johngmyers commented
Please add an entry to CHANGES

2023-05-02 14:55 UTC, gdasbach commented on http-client/src/main/java/com/proofpoint/http/client/jetty/JettyHttpClient.java
> +        getActiveConnections((AbstractConnectionPool) httpDestination.getConnectionPool()).stream()
I thought I had pushed that yesterday.  Will be in the next push

2023-05-02 17:32 UTC, johngmyers commented
Please squash and change title to "Upgrade Jetty to 10.0.15"

2023-05-04 20:18 UTC, gdasbach commented
> Please squash and change title to "Upgrade Jetty to 10.0.15"

Done

2023-05-04 22:38 UTC, johngmyers approved these changes

2023-05-04 23:23 UTC, merged