Allow the admin endpoint to have HSTS header
proofpoint/platform pull request #957
Opened 2024-03-07 16:16 UTC by tomjshore

This change is to allow the [HSTS headers ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#preloading_strict_transport_security) to be present on all admin endpoint.

Our security team we complaining that for a couple of admin endpoints that we added we needed this header. 

It is configured the same as normal by setting
jaxrs.hsts.max-age

2024-03-07 16:28 UTC, johngmyers approved these changes

2024-03-07 16:28 UTC, johngmyers requested changes
Please update the CHANGES file as well

2024-03-07 18:27 UTC, johngmyers requested changes

2024-03-07 18:27 UTC, johngmyers commented on CHANGES
> +  - Allow HSTS filters to admin endpoints
```suggestion
  - When HSTS headers are enabled (by configuring "jaxrs.hsts.max-age"), we now attach the
     Strict-Transport-Security header to responses from admin endpoints as well.
```

2024-03-08 09:30 UTC, tomjshore commented
All suggestions done.

2024-03-08 17:51 UTC, johngmyers approved these changes

2024-03-08 17:51 UTC, merged